// Code generated by "genflagged -type=groupOptions -outType=groupOptionsBitFlags -outFile=group_options_flagged.go"; DO NOT EDIT.
package promise

import "github.com/asmsh/flagged"

// groupOptionsBitFlags combines all flags from [groupOptions] as [flagged.BitFlags8].
type groupOptionsBitFlags flagged.BitFlags8

// _groupOptionsBitFlagsInterface includes all the methods generated for type [groupOptionsBitFlags].
type _groupOptionsBitFlagsInterface interface {
	BitFlags() flagged.BitFlags
	Clone() groupOptionsBitFlags
	TypedFlags() groupOptions
	SetTypedFlags(flags groupOptions)

	IsNeverCancelCBCtx() (set bool)
	SetNeverCancelCBCtx() (old bool)
	ResetNeverCancelCBCtx() (old bool)
	SetNeverCancelCBCtxTo(new bool) (old bool)
	ToggleNeverCancelCBCtx() (new bool)

	IsOnetimeHandling() (set bool)
	SetOnetimeHandling() (old bool)
	ResetOnetimeHandling() (old bool)
	SetOnetimeHandlingTo(new bool) (old bool)
	ToggleOnetimeHandling() (new bool)

	IsNoNilCtxDoneChan() (set bool)
	SetNoNilCtxDoneChan() (old bool)
	ResetNoNilCtxDoneChan() (old bool)
	SetNoNilCtxDoneChanTo(new bool) (old bool)
	ToggleNoNilCtxDoneChan() (new bool)

	IsNoWaitingBusyGroup() (set bool)
	SetNoWaitingBusyGroup() (old bool)
	ResetNoWaitingBusyGroup() (old bool)
	SetNoWaitingBusyGroupTo(new bool) (old bool)
	ToggleNoWaitingBusyGroup() (new bool)

	IsSaveAllGroupResults() (set bool)
	SetSaveAllGroupResults() (old bool)
	ResetSaveAllGroupResults() (old bool)
	SetSaveAllGroupResultsTo(new bool) (old bool)
	ToggleSaveAllGroupResults() (new bool)
}

// These are the indexes of the flags used by this generated code.
// Listed in the same order their corresponding fields are listed in [groupOptions].
const (
	_groupOptionsNeverCancelCBCtxBitIndex    flagged.BitIndex = iota // for field [groupOptions.neverCancelCBCtx]
	_groupOptionsOnetimeHandlingBitIndex     flagged.BitIndex = iota // for field [groupOptions.onetimeHandling]
	_groupOptionsNoNilCtxDoneChanBitIndex    flagged.BitIndex = iota // for field [groupOptions.noNilCtxDoneChan]
	_groupOptionsNoWaitingBusyGroupBitIndex  flagged.BitIndex = iota // for field [groupOptions.noWaitingBusyGroup]
	_groupOptionsSaveAllGroupResultsBitIndex flagged.BitIndex = iota // for field [groupOptions.saveAllGroupResults]
)

// BitFlags returns an interface to the underlying value.
func (f *groupOptionsBitFlags) BitFlags() flagged.BitFlags {
	return (*flagged.BitFlags8)(f)
}

// Clone returns a copy of the current flags value.
func (f *groupOptionsBitFlags) Clone() groupOptionsBitFlags {
	return *f
}

// TypedFlags returns a copy of the current flags value inside a typed
// object, which is the same used to generate the flags in first place.
func (f *groupOptionsBitFlags) TypedFlags() groupOptions {
	return groupOptions{
		neverCancelCBCtx:    f.IsNeverCancelCBCtx(),
		onetimeHandling:     f.IsOnetimeHandling(),
		noNilCtxDoneChan:    f.IsNoNilCtxDoneChan(),
		noWaitingBusyGroup:  f.IsNoWaitingBusyGroup(),
		saveAllGroupResults: f.IsSaveAllGroupResults(),
	}
}

// SetTypedFlags overrides the current flags value based on the typed
// object provided.
func (f *groupOptionsBitFlags) SetTypedFlags(flags groupOptions) {
	f.SetNeverCancelCBCtxTo(flags.neverCancelCBCtx)
	f.SetOnetimeHandlingTo(flags.onetimeHandling)
	f.SetNoNilCtxDoneChanTo(flags.noNilCtxDoneChan)
	f.SetNoWaitingBusyGroupTo(flags.noWaitingBusyGroup)
	f.SetSaveAllGroupResultsTo(flags.saveAllGroupResults)
}

func (f *groupOptionsBitFlags) IsNeverCancelCBCtx() (set bool) {
	return f.BitFlags().Is(_groupOptionsNeverCancelCBCtxBitIndex)
}
func (f *groupOptionsBitFlags) SetNeverCancelCBCtx() (old bool) {
	return f.SetNeverCancelCBCtxTo(true)
}
func (f *groupOptionsBitFlags) ResetNeverCancelCBCtx() (old bool) {
	return f.SetNeverCancelCBCtxTo(false)
}
func (f *groupOptionsBitFlags) SetNeverCancelCBCtxTo(new bool) (old bool) {
	return f.BitFlags().SetTo(_groupOptionsNeverCancelCBCtxBitIndex, new)
}
func (f *groupOptionsBitFlags) ToggleNeverCancelCBCtx() (new bool) {
	return f.BitFlags().Toggle(_groupOptionsNeverCancelCBCtxBitIndex)
}

func (f *groupOptionsBitFlags) IsOnetimeHandling() (set bool) {
	return f.BitFlags().Is(_groupOptionsOnetimeHandlingBitIndex)
}
func (f *groupOptionsBitFlags) SetOnetimeHandling() (old bool) {
	return f.SetOnetimeHandlingTo(true)
}
func (f *groupOptionsBitFlags) ResetOnetimeHandling() (old bool) {
	return f.SetOnetimeHandlingTo(false)
}
func (f *groupOptionsBitFlags) SetOnetimeHandlingTo(new bool) (old bool) {
	return f.BitFlags().SetTo(_groupOptionsOnetimeHandlingBitIndex, new)
}
func (f *groupOptionsBitFlags) ToggleOnetimeHandling() (new bool) {
	return f.BitFlags().Toggle(_groupOptionsOnetimeHandlingBitIndex)
}

func (f *groupOptionsBitFlags) IsNoNilCtxDoneChan() (set bool) {
	return f.BitFlags().Is(_groupOptionsNoNilCtxDoneChanBitIndex)
}
func (f *groupOptionsBitFlags) SetNoNilCtxDoneChan() (old bool) {
	return f.SetNoNilCtxDoneChanTo(true)
}
func (f *groupOptionsBitFlags) ResetNoNilCtxDoneChan() (old bool) {
	return f.SetNoNilCtxDoneChanTo(false)
}
func (f *groupOptionsBitFlags) SetNoNilCtxDoneChanTo(new bool) (old bool) {
	return f.BitFlags().SetTo(_groupOptionsNoNilCtxDoneChanBitIndex, new)
}
func (f *groupOptionsBitFlags) ToggleNoNilCtxDoneChan() (new bool) {
	return f.BitFlags().Toggle(_groupOptionsNoNilCtxDoneChanBitIndex)
}

func (f *groupOptionsBitFlags) IsNoWaitingBusyGroup() (set bool) {
	return f.BitFlags().Is(_groupOptionsNoWaitingBusyGroupBitIndex)
}
func (f *groupOptionsBitFlags) SetNoWaitingBusyGroup() (old bool) {
	return f.SetNoWaitingBusyGroupTo(true)
}
func (f *groupOptionsBitFlags) ResetNoWaitingBusyGroup() (old bool) {
	return f.SetNoWaitingBusyGroupTo(false)
}
func (f *groupOptionsBitFlags) SetNoWaitingBusyGroupTo(new bool) (old bool) {
	return f.BitFlags().SetTo(_groupOptionsNoWaitingBusyGroupBitIndex, new)
}
func (f *groupOptionsBitFlags) ToggleNoWaitingBusyGroup() (new bool) {
	return f.BitFlags().Toggle(_groupOptionsNoWaitingBusyGroupBitIndex)
}

func (f *groupOptionsBitFlags) IsSaveAllGroupResults() (set bool) {
	return f.BitFlags().Is(_groupOptionsSaveAllGroupResultsBitIndex)
}
func (f *groupOptionsBitFlags) SetSaveAllGroupResults() (old bool) {
	return f.SetSaveAllGroupResultsTo(true)
}
func (f *groupOptionsBitFlags) ResetSaveAllGroupResults() (old bool) {
	return f.SetSaveAllGroupResultsTo(false)
}
func (f *groupOptionsBitFlags) SetSaveAllGroupResultsTo(new bool) (old bool) {
	return f.BitFlags().SetTo(_groupOptionsSaveAllGroupResultsBitIndex, new)
}
func (f *groupOptionsBitFlags) ToggleSaveAllGroupResults() (new bool) {
	return f.BitFlags().Toggle(_groupOptionsSaveAllGroupResultsBitIndex)
}
